const endpoint = "/.netlify/functions/record-browser";
const state = { currentStart: null, nextCursor: null, trail: [], columns: [], catalog: [], mode: "observation", anchor: null };
const qs = new URLSearchParams(location.search);
const statusLine = document.querySelector("#records-status");
const table = document.querySelector("#records-table");
const picker = document.querySelector("#column-picker");
const day = document.querySelector("#record-day");
const at = document.querySelector("#record-at");
const newer = document.querySelector("#newer-records");
const older = document.querySelector("#older-records");

function localDay(value = new Date()) { const offset = value.getTimezoneOffset() * 60000; return new Date(value - offset).toISOString().slice(0, 10); }
function localDateTime(value = new Date()) { const offset = value.getTimezoneOffset() * 60000; return new Date(value - offset).toISOString().slice(0, 16); }
function time(value) { return value ? new Intl.DateTimeFormat(undefined, { dateStyle: "medium", timeStyle: "medium" }).format(new Date(value)) : "Unknown device time"; }
function escapeHtml(value) { return String(value ?? "").replace(/[&<>\"]/g, char => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" })[char]); }
function cell(field = { state: "missing" }) { if (field.state === "available") return escapeHtml(typeof field.value === "object" ? JSON.stringify(field.value) : field.value); if (field.state === "unavailable") return `<span class="unavailable-value">Unavailable · ${escapeHtml(field.reason)}</span>`; return `<span class="missing-value">Not in this older record</span>`; }
function updateButtons() { newer.disabled = !state.trail.length; older.disabled = !state.nextCursor; }
function renderColumns() { picker.innerHTML = state.catalog.map(item => `<label><input type="checkbox" value="${escapeHtml(item.name)}" ${state.columns.includes(item.name) ? "checked" : ""}>${escapeHtml(item.label)}${item.unit ? ` (${escapeHtml(item.unit)})` : ""}</label>`).join(""); picker.querySelectorAll("input").forEach(input => input.addEventListener("change", () => { state.columns = [...picker.querySelectorAll("input:checked")].map(box => box.value); load(); })); }
function render(records) {
  const headers = ["Observation time", "Session / cycle", "Release", "Receipt time", "Reasons", ...state.columns];
  table.innerHTML = `<div class="records-row records-head">${headers.map(escapeHtml).map(value => `<strong>${value}</strong>`).join("")}</div>` + (records.length ? records.map(record => `<div class="records-row"> <span>${time(record.observationTime)}${record.observationTime ? "" : "<br><small>Unsynchronized; use session/cycle navigation.</small>"}</span><span>${escapeHtml(record.sessionId)} / ${escapeHtml(record.cycleSequence ?? "—")}</span><span>${escapeHtml(record.rulesRelease?.releaseId || record.rulesRelease?.version || "Not recorded")}</span><span>${record.receiptTime ? time(record.receiptTime) : "Not stored"}</span><span>${escapeHtml(record.triggerReasons.map(reason => reason.kind).join(", "))}</span>${state.columns.map(name => `<span>${cell(record.fields[name])}</span>`).join("")}</div>`).join("") : `<p class="event-empty">No observation records match this position.</p>`);
}
async function request(url) { const response = await fetch(url, { cache: "no-store" }); const body = await response.json().catch(() => ({})); if (!response.ok) { const error = new Error(body.code || "read_failed"); error.body = body; throw error; } return body; }
async function load(cursor = null) {
  statusLine.textContent = "Loading durable records…";
  const params = new URLSearchParams({ columns: state.columns.join(",") }); if (cursor) params.set("cursor", cursor); if (qs.get("event")) params.set("event", qs.get("event")); if (!cursor && state.anchor && state.mode === "observation") params.set("anchor", state.anchor); if (qs.get("session")) { params.set("view", "session"); params.set("session", qs.get("session")); params.set("cycle", qs.get("cycle") || "0"); } else if (state.mode === "receipt") params.set("view", "receipt");
  try { const data = await request(`${endpoint}?${params}`); if (data.status === "configuration") { statusLine.textContent = "Saved rules are not available; record columns cannot be defined."; render([]); return; } state.catalog = data.catalog; if (!state.columns.length) { const defaults = data.defaultColumns?.length ? data.defaultColumns : data.catalog.slice(0, 6).map(item => item.name); if (defaults.length) { state.columns = defaults; renderColumns(); return load(cursor); } } state.currentStart = cursor; state.nextCursor = data.nextCursor; renderColumns(); render(data.records); statusLine.textContent = data.status === "empty" ? "No records at this position." : (data.source === "receipt-time-fallback" ? "Receipt-time fallback: this is cloud receipt time, not device observation time." : "Observation time is device-reported time. Receipt time is shown separately."); updateButtons(); } catch (error) { statusLine.textContent = error.body?.code === "configuration_missing" ? "Configuration is unavailable." : error.body?.code === "read_denied" ? "Record reading is denied by the current service configuration." : "Read failed. The page remains usable; try again."; }
}
async function exportDay() { const selected = new Date(`${day.value}T00:00:00`); const next = new Date(selected); next.setDate(next.getDate() + 1); statusLine.textContent = "Exporting the complete local day…"; try { const response = await fetch(`${endpoint}?view=export&start=${encodeURIComponent(selected.toISOString())}&end=${encodeURIComponent(next.toISOString())}`, { cache: "no-store" }); if (!response.ok) { const body = await response.json().catch(() => ({})); throw new Error(body.code || "export_failed"); } const text = await response.text(); const blob = new Blob([text], { type: "text/csv" }); const link = Object.assign(document.createElement("a"), { href: URL.createObjectURL(blob), download: `durable-observations-${day.value}.csv` }); link.click(); URL.revokeObjectURL(link.href); statusLine.textContent = `Export complete: ${response.headers.get("X-Export-Record-Count")} records.`; } catch (error) { statusLine.textContent = error.message === "export_too_large" ? "Export is too large to complete safely; narrow the day or investigate ingestion volume." : "Export failed; no partial file was presented as complete."; } }
async function history() { const panel = document.querySelector("#history-panel"); panel.hidden = false; try { const data = await request(`${endpoint}?view=history`); document.querySelector("#history-list").innerHTML = data.occurrences.map(item => { const open = item.open; const close = item.close; return `<article class="event-card ${open.severity.toLowerCase()}"><strong>${escapeHtml(open.severity)} · ${escapeHtml(open.displayName)}</strong><span>Opened ${time(open.opening?.observedAt || open.firstReportedAt)}</span><span>${close ? `Closed by ${escapeHtml(close.closeReason)}; detection ${time(close.detectedAt || close.restartDetectedAt)}. Device close time unknown.` : "Still open"}</span><a href="/records.html?session=${encodeURIComponent(open.sessionId)}&cycle=${Math.max(0, (open.opening?.cycleSequence || 0) - 3)}&event=${encodeURIComponent(open.eventDefinitionId)}">View nearby observations</a></article>`; }).join("") || "<p class='event-empty'>No V3 occurrences found.</p>"; } catch { document.querySelector("#history-list").textContent = "Event history is currently unavailable."; } }
day.value = localDay(); at.value = localDateTime(); document.querySelector("#timezone-label").textContent = `Displayed in ${Intl.DateTimeFormat().resolvedOptions().timeZone}; day boundaries adjust for daylight-saving time.`;
document.querySelector("#latest-records").addEventListener("click", () => { state.nextCursor = null; state.currentStart = null; state.trail = []; state.mode = "observation"; state.anchor = null; day.value = localDay(); at.value = localDateTime(); load(); }); document.querySelector("#receipt-records").addEventListener("click", () => { state.nextCursor = null; state.currentStart = null; state.trail = []; state.mode = "receipt"; state.anchor = null; load(); }); older.addEventListener("click", () => { if (state.nextCursor) { state.trail.push(state.currentStart); load(state.nextCursor); } }); newer.addEventListener("click", () => load(state.trail.pop() || null)); document.querySelector("#export-day").addEventListener("click", exportDay); at.addEventListener("change", () => { const selected = new Date(at.value); if (!Number.isFinite(selected.getTime())) return; state.mode = "observation"; state.anchor = selected.toISOString(); state.trail = []; load(); });
if (qs.get("history") === "1") history(); load();
